language: python
python:
- '2.7'
install:
- sudo apt-get update -qq
- sudo apt-get install -y libavformat-dev libswscale-dev libavdevice-dev freeglut3-dev check
- pip install -r requirements.txt
- python build_cbackend.py sample test/openvx_sample/
script:
- make -C test
deploy:
  provider: pypi
  user: hakanardo
  password:
    secure: LA16LJyigOhZPqBulP/jT0DbM8cDnGma5y/7ldiHpEJTuKUYQ9VJSKDnxYXPRnTyWtQT2VioQtqMES3m8djBsrI8mm85heJUDI67EyRl7g/MEljBiSeida2VTwlY4U5INBuCyijQ5j52U1C2SOKksnBIaO7yh2MuOL4M/nMnIWI=
  on:
    branch: stable
