language: python
python:
- '2.7'
install:
- sudo apt-get update -qq
- sudo apt-get install -y libavformat-dev libswscale-dev libavdevice-dev freeglut3-dev check
- pip install -r requirements.txt
- curl https://www.khronos.org/registry/vx/sample/openvx_sample_1.0.1.tar.bz2 | tar xf -
- cd openvx_sample && python Build.py --os=Linux
- python build_cbackend.py sample openvx_sample/install/Linux/x64/Release/
script:
- make -C test
deploy:
  provider: pypi
  user: hakanardo
  password:
    secure: LA16LJyigOhZPqBulP/jT0DbM8cDnGma5y/7ldiHpEJTuKUYQ9VJSKDnxYXPRnTyWtQT2VioQtqMES3m8djBsrI8mm85heJUDI67EyRl7g/MEljBiSeida2VTwlY4U5INBuCyijQ5j52U1C2SOKksnBIaO7yh2MuOL4M/nMnIWI=
  on:
    branch: stable
